Gemfile.lock, README.md, futurism.gemspec, javascript/elements/index.js, javascript/futurism_channel.js, lib/futurism.rb, lib/futurism/channel.rb, lib/futurism/helpers.rb, test/cable/channel_test.rb, test/dummy/app/views/posts/_card.html.erb, test/test_helper.rb
Allows `futurize` to be called with a `partial` keyword
Changed the internal implementation to use `ActiveSupport::MessageVerifier`
=> Allow to use arbitrary partials

README.md, lib/futurism/helpers.rb
Enhancement
All calls to the `futurize` helper now accept a new parameter, `html_options` which is a hash. This gets passed directly to `content_tag`.
eg.
```html
<%= futurize @posts, extends: :tr, html_options: {style: "color: red"} do %>
<td class="placeholder">&nbsp;</td>
<% end %>
```
will produce:
```html
<tr data-signed-params="BAhvOglQb3N0EDoQQG5ld19yZWNvcmRGOhBAYXR0cmlidXRlc286HkFjdGl2ZU1vZGVsOjpBdHRyaWJ1dGVTZXQGOwdVOiNBY3RpdmVNb2RlbDo6TGF6eUF0dHJpYnV0ZUhhc2hbCn0JSSIHaWQGOgZFVG86H0FjdGl2ZU1vZGVsOjpUeXBlOjpJbnRlZ2VyCToPQHByZWNpc2lvbjA6C0BzY2FsZTA6C0BsaW1pdGkNOgtAcmFuZ2VvOgpSYW5nZQg6CWV4Y2xUOgpiZWdpbmwtCQAAAAAAAACAOghlbmRsKwkAAAAAAAAAgEkiCnRpdGxlBjsKVG86HkFjdGl2ZU1vZGVsOjpUeXBlOjpTdHJpbmcIOwwwOw0wOw4wSSIPY3JlYXRlZF9hdAY7ClRVOkpBY3RpdmVSZWNvcmQ6OkF0dHJpYnV0ZU1ldGhvZHM6OlRpbWVab25lQ29u …
```
=> enable passing of html_options hash

README.md, javascript/futurism_channel.js
enhancement
Whenever data is received and CableReady has performed its actions, dispatch the `futurism:appear` event.
Note: I'm not certain if this is exactly what you had in mind, so I am open to any suggestions. I just think this is a great library and wanted to help quickly.
Fixes # (issue)
Resolves #19
=> Dispatch futurism:appear method

lib/futurism/helpers.rb
Minor enhancement
Uses the `#klass` method on a collection to get the class being wrapped.
`#klass` returns the collection's class even when it's empty.
```
User.none.first.class.name
=> "NilClass"
User.none.klass.name
=> "User"
```
=> uses AR Collection klass method

lib/futurism/helpers.rb, test/cable/channel_test.rb
Feature
This PR implements the suggested solution as described in #27. It allows pass `locals` when rendering a collection with `futurize`:
```html+erb
<%= futurize partial: 'items/card', collection: @cards, as: :card, extends: :div, locals: { selected: true } do %>
<div class="spinner"></div>
<% end %>
```
Resolves #27.
In order to stay as close as possible to the `render` method in Rails it makes sense to support the passing of locals when rendering a collection.
=> Allow to pass locals when rendering a collection

lib/futurism/helpers.rb, test/cable/channel_test.rb
Enhancement
This PR allows to specify `:as` when rendering a collection. With this you can name the local variable which is getting passed to your partial.
Example:
```html+erb
<%= futurize partial: 'items/card', collection: @cards, as: :card_item, extends: :div do %>
<div class="spinner"></div>
<% end %>
```
Similar to #28 this PR aims to bring `futurize` closer to the Rails `render` method.
=> Allow to specify :as when rendering a collection

.github/ISSUE_TEMPLATE/bug_report.md
Fix
Update the bug report template to feature Futurism and CableReady.
No confusion when someone tries to file a bug 😉 
Plus it could be good to know what version of CableReady is being used since they are "heavily related".
=> Update bug report template to feature 'Futurism'

lib/futurism/channel.rb, test/cable/channel_test.rb, test/dummy/app/views/posts/_card.html.erb
Bug fix
Fixes #20
Url generation in rendered partials should now work. The reason was that the incorrect `SCRIPT_NAME` from `connection.env` was applied here: https://github.com/rails/rails/blob/b13a5cb83ea00d6a3d71320fd276ca21049c2544/actionpack/lib/action_controller/metal/url_for.rb
=> 20 fix generated urls

javascript/futurism_channel.js, lib/futurism/channel.rb, lib/futurism/helpers.rb, test/cable/channel_test.rb, test/helper/helper_test.rb
Clean up the internals a bit, create a wrapper class for a futurism `Element`
=> Refactor element - use SGIDs where possible to minimize over-the-wire size

README.md, lib/futurism/channel.rb, test/cable/channel_test.rb
This PR adds ActionCable identifiers.
Fixes #34
This should prevent any users seeing updates from other users and relies on `identified_by` in `ApplicationCable::Connection`
=> 34 identify channel

lib/futurism/helpers.rb, test/helper/helper_test.rb
* Allow data attributes to be passed in html_options, without removing `sgid`, `signed_params`
* Disallow overwriting `sgid`, `signed_params` data-attributes
Fixes https://github.com/julianrubisch/futurism/issues/43
Allows Futurism to respect developers wishes to pass in data-attributes e.g. Stimulus controllers
=> Add data attributes from html options

README.md
Add a Gotcha section with a hint on how to fix the ActiveStorage URL error in development.
Fixes #30
=> Add Gotcha hint to README #39

javascript/elements/futurism_element.js, javascript/elements/futurism_li.js, javascript/elements/futurism_table_row.js, javascript/elements/futurism_utils.js, lib/futurism/helpers.rb, test/helper/helper_test.rb
Allow eager loading of invisible content, e.g. for tabs.
This PR adds an `eager: true` option you can specify in your `futurize` call that will render a `data-eager="true"` attribute on `<futurism-element>`.
If this attribute is present, the JS will disconnect any present `IntersectionObserver` and straight away call the `futurism:appear` event.
Fixes #42
While it may seem counterintuitive at first, this is actually a good idea if you have invisible content that you still want to skip in your initially rendered HTML, e.g. hidden forms or tabs.
It might still lead to increased bandwidth usage, so use sparingly.
=> 42 eager loading

javascript/elements/futurism_utils.js, javascript/elements/index.js, javascript/utils/crypto.js
This PR addresses the "flash of manipulated content" that occurs if you do a Turbolinks restoration visit (you navigate back, see a flash of the cached - rendered - content before the placeholders appear again and the page is fetched and reloaded).
Not only is this confusing to the user, it can also serve stale content which then gets updated again when the server fetch succeeds. A better strategy is to re-render the placeholders before Turbolinks caching starts.
To achieve that, I resorted to `sessionStorage` (it seemed a better fit than `localStorage` because it clears automatically when a user quits the session) to save the placeholder elements under a key that represents the `outerHTML` as a SHA256 hash.
That same hash is stored as a `data-futurism-hash` attribute on the rendered …
=> Reset before turbolinks caching

README.md, lib/futurism.rb, lib/futurism/helpers.rb
This adds a `Futurism.skip_in_test` configuration flag, so lazy loading can be skipped in Rails system tests etc.
=> Add skip_in_test flag

Gemfile.lock, futurism.gemspec, javascript/futurism_channel.js, lib/futurism.rb, lib/futurism/channel.rb, lib/futurism/message_verifier.rb, lib/futurism/resolver/controller.rb, lib/futurism/resolver/controller/renderer.rb, test/cable/channel_test.rb, test/dummy/app/controllers/home_controller.rb, test/dummy/config/routes.rb, test/resolver/controller/renderer_test.rb, test/resolver/controller_test.rb, test/test_helper.rb
This PR sends the current url (`window.location.href`) down the wire on each request. This URL is then parsed and the context for the query parameters is passed to the appropriate controller. Specifically, this will allow `params` to be used inside of helper methods or view templates properly
Fixes #54 
Note: this changes up the test suite for channel tests quite a bit and restructures how and where controllers and their renders are resolved. This is to primarily simplify the object's roles and to make testing much easier.
=> Pass url on each request and parse to build params hash

README.md, lib/futurism.rb, lib/futurism/resolver/controller.rb, test/futurism_test.rb
This is a PR changes the way futurism's `default_controller` is resolved. Previously, you could only set as a constant (i.e. `MyController`), but now you can set as `"MyController"` and it will be converted to the constant upon use.  This is to address a zietwork autoload issue as outlined in #68 
NOTE: This is a commit that is based on #69 and shouldn't be merged until that PR is merged.
Fixes #68
=> Lazily load default controller

lib/futurism/helpers.rb, test/cable/channel_test.rb
Makes the `#{partial}_counter` variable available to futurized partials (cf https://guides.rubyonrails.org/layouts_and_rendering.html#local-variables)
=> Allow rendered partials to use the `partial_counter` variable

javascript/elements/index.js
Adapts the caching and restoring of placeholders for `turbo` events
Fixes #82
=> Add turbo events #82

lib/futurism/helpers.rb, test/cable/channel_test.rb, test/dummy/app/models/action_item.rb, test/dummy/db/migrate/2021042923813_create_action_items.rb, test/dummy/db/schema.rb, test/helper/helper_test.rb
This would mean an object such as `ActionItem` when evaluated in a partial would show up as `actionitem` by default, instead of the expected `action_item`. Users of the library could override this with the `as:` option, such as `as: :action_item` in this case.
Prior to the change, this code would be need:
```erb
<!-- index.html.erb --!>
<%= futurize(collection: ActionItem.all, extends: :div)  { } %>
<!-- _action_item.html.erb --!>
<%= actionitem.description %>
```
Whereas, we would expect the following to work
```erb
<!-- index.html.erb --!>
<%= futurize(collection: ActionItem.all, extends: :div)  { } %>
<!-- _action_item.html.erb --!>
<%= action_item.description %>
```
This follows Rails conventions and the principle of least surprise. However, this is a breaking change for users of this …
=> Use rails convention to underscore collection class names

lib/futurism/helpers.rb, test/helper/helper_test.rb
Allows any local to be a GlobalId-able object
Fixes #91
=> Support GlobalId objects

lib/futurism/resolver/controller/renderer.rb, test/dummy/config/routes.rb, test/resolver/controller/renderer_test.rb
This passes in the full url to the `Rails.application.routes.recognize_path` method and try multiple HTTP methods to try to match a URL.
Note: While this does fix some bugs, it doesn't appear the `controller` and `action_name` are currently being passed through correctly to the underlying controller. I don't have failing tests for that, but it doesn't look like the code I wrote some time ago works properly. 
This PR does no harm -- it makes it better -- but it doesn't fully address the intended functionality. However, it does fix #89
=> Better recognize urls

lib/futurism.rb, lib/futurism/resolver/resources.rb, test/cable/channel_test.rb, test/test_helper.rb
In development and test, we render a short version of the error message (and a hidden backtrace) to be able to catch typos, bugs in our partials, etc.
Fixes #63 
While developing you're not often watching the logs to see what's happening. This will output a fairly obvious error message and the backtrace is hidden (via `display: none;`
=> Better errors

README.md, javascript/futurism_channel.js, lib/futurism/channel.rb, lib/futurism/helpers.rb, lib/futurism/resolver/resources.rb, test/cable/channel_test.rb, test/helper/helper_test.rb
Allows to define an option called `broadcast_each` on a collection that will issue individual `cable_ready.broadcast` calls for each element
Closes #79
=> Broadcast_each

README.md, lib/futurism/helpers.rb, test/helper/helper_test.rb
Passes a `record` and `index` arguments to any `futurize` placeholder block rendered either for an `ActiveRecord::Base` or any type of collection.
I.e. you can do
```erb
<%= futurize Post.all .... do |post, index| %>
<li><%= index + 1 %>. <%= post.title %></li>
<% end %>
```
Fixes #104
=> Contextual placeholder arguments

javascript/elements/index.js
- Possibly related to #72 , but i could see an issue where the events are firing before the polyfill is loaded.
Run polyfill before defining elements
🤷
=> fix: run polyfill before eventListeners

.github/workflows/standardrb.yml
Enhancement.
[actions/setup-ruby](https://github.com/actions/setup-ruby) is deprecated and should be replaced with the maintained [ruby/setup-ruby](https://github.com/ruby/setup-ruby)
Keep GH actions updated and remove deprecated dependencies.
=> Update GH action

lib/futurism/helpers.rb, test/cable/channel_test.rb, test/helper/helper_test.rb
Enhancement
Sets the default extends option to `:div`, which removes the need to repeatedly type `extends: :div` when using the futurize helper method :tada:
Fixes https://github.com/stimulusreflex/futurism/issues/127
Developer happiness; reduces boilerplate.
=> Default :extends option

javascript/elements/futurism_utils.js
Bugfix.
Resolves an issue with the `eager` option.
For elements using `IntersectionObserver` a retry mechanism is used for binding `dispatchAppearEvent` [here](https://github.com/stimulusreflex/futurism/blob/8d352a54a3f35bc2f7856774d6edefbd521d4fbf/javascript/elements/futurism_utils.js#L45). 
That same retry mechanism wasn't being used for elements using eager loading.
If it's not used, the calls to replace the element happen before the channel has been initialized on the client side, and the element doesn't get replaced.
Fixes #122 
Fixes loading elements with `eager: true`, and also fixes futurising partials without passing a block (#122).
=> Use retries with extendElementWithEagerLoading

README.md, app/channels/futurism/channel.rb, lib/futurism.rb, lib/futurism/configuration.rb, lib/futurism/version.rb
This makes the connection able to use the Application::Connection in the same way reflex does. It is over-ridable. 
Now you can inherit your application's Action Cable connection and not have to monkey patch things.
=> Configurable channel

README.md, lib/futurism.rb, lib/futurism/engine.rb, lib/futurism/helpers.rb, lib/futurism/resolver/controller/instrumentation.rb, lib/futurism/resolver/controller/renderer.rb, test/futurism_test.rb, test/resolver/controller/instrumentation_test.rb, test/resolver/controller_test.rb, test/support/helpers.rb, test/test_helper.rb
Feature
Add a new configuration option `Futurism.instrumentation`.
When enabled, ActiveSupport notification event `render.futurism` is emitted on render calls.
Additionally, delay the initialization of the logger until the Rails application's logger is initialized and enhance the handling of configuration options to handle blank ENV values.
This is useful for performance monitoring, specifically for tracking the source of `futurize` calls.
=> Add instrumentation

javascript/elements/futurism_utils.js, javascript/elements/index.js, javascript/futurism_channel.js
When navigating a part of the page using Turbo Frames, in case of [promoting to a normal page visit](https://turbo.hotwired.dev/handbook/frames#promoting-a-frame-navigation-to-a-page-visit), the placeholders would be replaced but never resolve again.
The reason for this is that the [`turbo:before-cache`](https://turbo.hotwired.dev/reference/events#turbo%3Abefore-cache) event fires on a regular visit, so placeholders will be restored in order to be put into the Turbo cache afterwards. Contrary to a regular page visit, though, the whole page body will **not** be replaced, so the placeholders remain unresolved.
This would have been an easy fix if the `turbo:before-cache` event would have exposed an `event.detail` pointing to something usable, like the targeted Turbo Frame. Since it does not, …
=> Opt out of restoring placeholders for a promoted TF navigation
